version: 0.1

phases:
  install:
    commands:
      - echo ### installing maven ###
      - apt-get update -y
      - apt-get install -y software-properties-common
      - add-apt-repository ppa:openjdk-r/ppa
      - apt-get update -y
      - apt-get install -y openjdk-8-jdk-headless
      - echo apt-get install -y maven
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - eval $(aws ecr get-login --no-include-email --region=us-east-1 | sed 's|https://||')
  build:
    commands:
      - echo Build started on `date`
      - echo Trying a plain old compile
      - javac HelloWorld.java
      - echo Now we go with maven
      - echo mvn install -X
      - echo Building the Docker image...
      - docker build -t codebuild-poc-20190416 . 
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Tagging image
      - docker tag codebuild-poc-20190416:latest 397090398856.dkr.ecr.us-east-1.amazonaws.com/codebuild-poc-20190416
      - echo Pushing the Docker image...
      - docker push 397090398856.dkr.ecr.us-east-1.amazonaws.com/codebuild-poc-20190416
